### PR TITLE
Generate Python, Lua and Go bindings through SWIG

### PR DESCRIPTION
**Pull request by gokceneraslan**
These commits introduce a SWIG interface file (`bindings/quackle.i`) along with a simple Makefile to generate Python, Lua and Go bindings for all of `libquackle` and most of `libquackleio`.

In order to generate bindings, I made minimal changes to the existing code base: Qt dependencies of quackleio is the biggest obstacle for generating simple language bindings for quackle in general. Mostly required part of quackleio was GCGIO class which only works with `QTextStream` instances. So I added a simpler GCG file loader method which only makes use of a `QString`. So we can now use string conversion methods in `quackleio/util.cpp` to convert strings from/to `QString` and read/write GCG files conveniently. But in the long run getting rid of all Qt dependencies of quackleio would be the best decision, IMHO. At least, writing `std::string` counterparts would make things easier for the bindings.

I have also added simple test scripts for Python based on the existing test file (`test/testharness.cpp`).

### CODE REVIEW

**Comment by igungor** [comment]
I wrote a command-line game using the generated Go bindings, thanks to @gokceneraslan. The game uses Turkish alphabet and there are shortcomings here and there but you can play it right now.

https://github.com/igungor/bingo

**Comment by jfultz** [comment]
Just FYI, I'm not ignoring this pull request.  But don't know anything about SWIG, and I want to do a little due diligence on the review before merging.  Which will happen as time allows...

**Comment by gokceneraslan** [comment]
Thanks! No problem. I am not experienced in SWIG, either. I just thought that it would be nice to have some bindings for quackle API.

**Comment by doksides** [comment]
Can we possibly have PHP bindings please **gokceneraslan**?. Would have liked to venture into that myself but sadly I have no C++ skills whatsoever to speak of.

**Comment by gokceneraslan** [comment]
I have added PHP 5.6 but I do not guarantee any kind of maintenance. It seems it compiles and loads just fine on Linux.

**Comment by doksides** [comment]
Many thanks **gokceneraslan**!

**Pull request merged**
