### PR TITLE
OSPS Update 33

### PR DESCRIPTION
**Pull request by alkamid**
The DAWG file includes the latest update to OSPS from 25/07/2016. The details of the update can be found here: http://www.pfs.org.pl/osps/Update33.xls

### CODE REVIEW

**Comment by jfultz** [comment]
Is it useful to have both old and new versions of the dictionary, rather than just replacing the dictionary as you've done?

**Comment by alkamid** [comment]
IMHO — not really. This is a minor update with a few error corrections. When the long-awaited major update is available (hopefuly within the next year), we could leave both versions of the dictionary, but right now it's not worth it.

**Comment by jfultz** [comment]
I don't think this DAWG file is right.  Or, at least, it doesn't seem to bear any resemblance to the Excel file you pointed to.  For example, in the current OSPS, do a word search on "AIMK", and you get "KAMI", "KIMA", "MAKI", "MIKA".  In your new dictionary, it returns those words, plus "IMAK" and "MAIK".  Neither of those words are in your Excel file, but AMIK is, which is nowhere to be seen.  There are various other inconsistencies I found pretty quickly, too.

**Comment by alkamid** [comment]
@jfultz Sorry, I should have been clearer about what the linked file comprises. There are two tabs in the spreadsheet: "Dodane" (added words) and "Usunięte" (deleted words). The first column is the added/removed word, and the second is its base form. AMIK is in the "removed" list, so it correctly doesn't show up with the new file.

**Comment by jfultz** [comment]
But what about IMAK and MAIK, which appear nowhere in your spreadsheet, but which are new to your dictionary?

**Comment by alkamid** [comment]
That's weird. On my freshly downloaded and compiled Quackle, I do get IMAK and MAIK from the "old" OSPS (which is correct).

**Comment by jfultz** [comment]
Hmm...okay.  Now I am, too.  Okay...I'll just chalk it up to senility, then. :)

**Pull request merged**
