### PR TITLE
Update Norwegian dictionary.

### PR DESCRIPTION
**Pull request by sesse**
This is the April 2020 refresh of the same dictionary as the one already used
for Norwegian, namely the NSF (Norwegian Scrabble Association) word list.
It adds a lot of new words, and mainly removes questionable conjugations.

Source: http://www2.scrabbleforbundet.no/?p=4527

### CODE REVIEW

**Comment by sesse** [comment]
FWIW, I couldn't find a standalone tool for creating the DAWG, so I used the UI to add a new lexicon, called it nsf2020, added the word list, and renamed the file /home/sesse/.local/share/Quackle.org/Quackle/lexica/nsf2020.dawg. This seems to have created something that works (e.g. ABACA is now accepted).

**Comment by alkamid** [comment]
@sesse , I use https://github.com/quackle/quackle/tree/master/makeminidawg to create Polish DAWGs.

**Comment by sesse** [comment]
OK, thanks. Shouldn't this really be part of the build process, though? I mean, shipping the DAWG files only sounds dubious GPL-wise (they can hardly be considered the preferred form of modification), and shipping both the raw files and the DAWG files is a bit wasteful, plus increases the odds they can go out of sync.

**Comment by jfultz** [comment]
@sesse, thanks for your contribution!  I want to look at things a bit before approving, which I hope to do in the next few days.  In the mean time, some responses to the discussion...

The release doesn't ship raw files.

As for making it part of the build process, there are some lexicons which I don't have permissions to post to GitHub in raw form.  All raw lexicons are under version control *somewhere*, but not all of them are on GitHub (some are only on my development machines).  I prefer to maintain the possibility for people other than me to roll a full release, so the simplest solution was to just put all DAWGs under version control.

Yes, I could create a build process which would build some and not others.  But that's not how I prefer to spend my (limited) time.

Note that using the UI should be equivalent to running `makeminidawg`.

**Comment by sesse** [comment]
OK, so GPLv3 only applies to the program, not the dictionaries? That's a good clarification. And yes, I do understand that build systems are not the most fun topic…

**Comment by jfultz** [comment]
Yup...I added this to the LICENSE file last year after it just kind of struck me out of thin air that I had the previous language unintentionally suggested that I had the right to redistribute those files under the GPL, which I definitely do not have.

8e69b7994d91a8c

**Comment by alkamid** [comment]
@sesse would it be too much effort to run SPSA for Polish (OSPS)? We're using the default worths at the moment, and this seems to be a low hanging fruit for a significant improvement.

**Comment by sesse** [comment]
Perhaps I should rather just publish the code somewhere? It's hackish (nowhere near the quality to get it into a PR), but it's probably better than me trying to tune every language under the sun. Especially with the GADDAG and other optimizations, it should be fairly fast (something like 8 hours on a single core for 100k games, I can't recall).

**Comment by alkamid** [comment]
> Perhaps I should rather just publish the code somewhere?
I'd really appreciate that!

**Comment by sesse** [comment]
https://storage.sesse.net/quackle-spsa.diff

I've been using this command line:

./test --mode=selfplay --computer='Speedy Player' --repetitions=100000 --seed=1723441  --lexicon=norwegian --alphabet=norwegian

I believe it should be possible to tune Syn2 with SPSA as well (I haven't tried), although one probably should keep values that haven't been seen by at least one player. (Otherwise, values like the ones for two blanks will mostly fluctuate randomly.) Superleaves would need something radically different.

vcplace seems not to be used at all; the loading code should probably just be taken out?

**Comment by sesse** [comment]
Giving up after a month.

**Pull request closed without merging**
