### PR TITLE
Add Turkish alphabet and lexicon

### PR DESCRIPTION
**Pull request by gokceneraslan**

### CODE REVIEW

**Comment by jfultz** [comment]
Where did the dictionary come from?  Is there anyone who might potentially dispute this wordlist being redistributed with Quackle?

**Comment by gokceneraslan** [comment]
As I've written in https://github.com/quackle/quackle/pull/34#commitcomment-15241899, the wordlist is derived from an Apache-licensed Turkish spell checking framework and it is already being distributed with it. I'm not sure but they probably derived the wordlist from the official dictionary of Turkish Language Institution (http://www.tdk.gov.tr/)

**Comment by gokceneraslan** [comment]
Thanks!

**Comment by gokceneraslan** [comment]
It would be nice to add this to the release notes as well.

**Comment by jfultz** [comment]
Sorry, this somehow completely escaped my notice.

**Pull request merged**
